export const initialWarframes = [
    {
        name: 'Ash',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'radiation',
        hasLeverian: true,
        releaseYear: 2012,
        image: require('../assets/webp/ash.webp'),
    },
    {
        name: 'Ash Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'radiation',
        hasLeverian: true,
        releaseYear: 2015,
        image: require('../assets/webp/ash-prime.webp'),
    },
    {
        name: 'Atlas',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'toxin',
        hasLeverian: true,
        releaseYear: 2015,
        image: require('../assets/webp/atlas.webp'),
    },
    {
        name: 'Atlas Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'toxin',
        hasLeverian: true,
        releaseYear: 2019,
        image: require('../assets/webp/atlas-prime.webp'),
    },
    {
        name: 'Banshee',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        hasLeverian: false,
        releaseYear: 2013,
        image: require('../assets/webp/banshee.webp'),
    },
    {
        name: 'Banshee Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        hasLeverian: false,
        releaseYear: 2017,
        image: require('../assets/webp/banshee-prime.webp'),
    },
    {
        name: 'Baruuk',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'impact',
        hasLeverian: false,
        releaseYear: 2018,
        image: require('../assets/webp/baruuk.webp'),
    },
    {
        name: 'Baruuk Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'impact',
        hasLeverian: false,
        releaseYear: 2022,
        image: require('../assets/webp/baruuk-prime.webp'),
    },
    {
        name: 'Caliban',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'electricity',
        hasLeverian: false,
        releaseYear: 2021,
        image: require('../assets/webp/caliban.webp'),
    },
    {
        name: 'Chroma',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'heat',
        hasLeverian: false,
        releaseYear: 2015,
        image: require('../assets/webp/chroma.webp'),
    },
    {
        name: 'Chroma Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'heat',
        hasLeverian: false,
        releaseYear: 2018,
        image: require('../assets/webp/chroma-prime.webp'),
    },
    {
        name: 'Citrine',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        hasLeverian: false,
        releaseYear: 2023,
        image: require('../assets/webp/citrine.webp'),
    },
    {
        name: 'Cyte-09',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'magnetic',
        hasLeverian: false,
        releaseYear: 2024,
        image: require('../assets/webp/cyte-09.webp'),
    },
    {
        name: 'Dagath',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['zenurik'],
        progenitorElement: 'toxin',
        hasLeverian: false,
        releaseYear: 2023,
        image: require('../assets/webp/dagath.webp'),
    },
    {
        name: 'Dante',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['universal'],
        progenitorElement: 'impact',
        hasLeverian: true,
        releaseYear: 2024,
        image: require('../assets/webp/dante.webp'),
    },
    {
        name: 'Ember',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'heat',
        hasLeverian: false,
        releaseYear: 2012,
        image: require('../assets/webp/ember.webp'),
    },
    {
        name: 'Ember Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'heat',
        hasLeverian: false,
        releaseYear: 2013,
        image: require('../assets/webp/ember-prime.webp'),
    },
    {
        name: 'Equinox',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        hasLeverian: false,
        releaseYear: 2015,
        image: require('../assets/webp/equinox.webp'),
    },
    {
        name: 'Equinox Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        hasLeverian: false,
        releaseYear: 2019,
        image: require('../assets/webp/equinox-prime.webp'),
    },
    {
        name: 'Excalibur',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['none'],
        progenitorElement: 'electricity',
        hasLeverian: false,
        releaseYear: 2012,
        image: require('../assets/webp/excalibur.webp'),
    },
    {
        name: 'Excalibur Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        hasLeverian: false,
        releaseYear: 2012,
        image: require('../assets/webp/excalibur-prime.webp'),
    },
    {
        name: 'Excalibur Umbra',
        gender: 'male',
        primeUmbra: 'umbra',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        hasLeverian: false,
        releaseYear: 2018,
        image: require('../assets/webp/excalibur-umbra.webp'),
    },
    {
        name: 'Frost',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'cold',
        hasLeverian: false,
        releaseYear: 2013,
        image: require('../assets/webp/frost.webp'),
    },
    {
        name: 'Frost Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['vazarin'],
        progenitorElement: 'cold',
        hasLeverian: false,
        releaseYear: 2013,
        image: require('../assets/webp/frost-prime.webp'),
    },
    {
        name: 'Gara',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'cold',
        hasLeverian: false,
        releaseYear: 2017,
        image: require('../assets/webp/gara.webp'),
    },
    {
        name: 'Gara Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['vazarin'],
        progenitorElement: 'cold',
        hasLeverian: false,
        releaseYear: 2021,
        image: require('../assets/webp/gara-prime.webp'),
    },
    {
        name: 'Garuda',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'radiation',
        hasLeverian: false,
        releaseYear: 2018,
        image: require('../assets/webp/garuda.webp'),
    },
    {
        name: 'Garuda Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'radiation',
        hasLeverian: false,
        releaseYear: 2022,
        image: require('../assets/webp/garuda-prime.webp'),
    },
    {
        name: 'Gauss',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'impact',
        hasLeverian: true,
        releaseYear: 2019,
        image: require('../assets/webp/gauss.webp'),
    },
    {
        name: 'Gauss Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'impact',
        hasLeverian: true,
        releaseYear: 2024,
        image: require('../assets/webp/gauss-prime.webp'),
    },
    {
        name: 'Grendel',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'impact',
        hasLeverian: true,
        releaseYear: 2019,
        image: require('../assets/webp/grendel.webp'),
    },
    {
        name: 'Grendel Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'impact',
        hasLeverian: true,
        releaseYear: 2023,
        image: require('../assets/webp/grendel-prime.webp'),
    },
    {
        name: 'Gyre',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'electricity',
        hasLeverian: false,
        releaseYear: 2022,
        image: require('../assets/webp/gyre.webp'),
    },
    {
        name: 'Harrow',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        hasLeverian: false,
        releaseYear: 2017,
        image: require('../assets/webp/harrow.webp'),
    },
    {
        name: 'Harrow Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        hasLeverian: false,
        releaseYear: 2021,
        image: require('../assets/webp/harrow-prime.webp'),
    },
    {
        name: 'Hildryn',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'cold',
        hasLeverian: false,
        releaseYear: 2019,
        image: require('../assets/webp/hildryn.webp'),
    },
    {
        name: 'Hildryn Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'cold',
        hasLeverian: false,
        releaseYear: 2023,
        image: require('../assets/webp/hildryn-prime.webp'),
    },
    {
        name: 'Hydroid',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        hasLeverian: false,
        releaseYear: 2014,
        image: require('../assets/webp/hydroid.webp'),
    },
    {
        name: 'Hydroid Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        hasLeverian: false,
        releaseYear: 2017,
        image: require('../assets/webp/hydroid-prime.webp'),
    },
    {
        name: 'Inaros',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        hasLeverian: false,
        releaseYear: 2016,
        image: require('../assets/webp/inaros.webp'),
    },
    {
        name: 'Inaros Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        hasLeverian: false,
        releaseYear: 2020,
        image: require('../assets/webp/inaros-prime.webp'),
    },
    {
        name: 'Ivara',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'toxin',
        hasLeverian: true,
        releaseYear: 2015,
        image: require('../assets/webp/ivara.webp'),
    },
    {
        name: 'Ivara Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'toxin',
        hasLeverian: true,
        releaseYear: 2019,
        image: require('../assets/webp/ivara-prime.webp'),
    },
    {
        name: 'Jade',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['universal', 'madurai'],
        progenitorElement: 'heat',
        hasLeverian: false,
        releaseYear: 2024,
        image: require('../assets/webp/jade.webp'),
    },
    {
        name: 'Khora',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'toxin',
        hasLeverian: false,
        releaseYear: 2018,
        image: require('../assets/webp/khora.webp'),
    },
    {
        name: 'Khora Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['vazarin'],
        progenitorElement: 'toxin',
        hasLeverian: false,
        releaseYear: 2022,
        image: require('../assets/webp/khora-prime.webp'),
    },
    {
        name: 'Koumei',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'cold',
        hasLeverian: false,
        releaseYear: 2024,
        image: require('../assets/webp/koumei.webp'),
    },
    {
        name: 'Kullervo',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        hasLeverian: false,
        releaseYear: 2023,
        image: require('../assets/webp/kullervo.webp'),
    },
    {
        name: 'Lavos',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        hasLeverian: true,
        releaseYear: 2020,
        image: require('../assets/webp/lavos.webp'),
    },
    {
        name: 'Lavos Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        hasLeverian: true,
        releaseYear: 2025,
        image: require('../assets/webp/lavos-prime.webp'),
    },
    {
        name: 'Limbo',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'electricity',
        hasLeverian: false,
        releaseYear: 2014,
        image: require('../assets/webp/limbo.webp'),
    },
    {
        name: 'Limbo Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'electricity',
        hasLeverian: false,
        releaseYear: 2018,
        image: require('../assets/webp/limbo-prime.webp'),
    },
    {
        name: 'Loki',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        hasLeverian: false,
        releaseYear: 2012,
        image: require('../assets/webp/loki.webp'),
    },
    {
        name: 'Loki Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        hasLeverian: false,
        releaseYear: 2014,
        image: require('../assets/webp/loki-prime.webp'),
    },
    {
        name: 'Mag',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'magnetic',
        hasLeverian: false,
        releaseYear: 2012,
        image: require('../assets/webp/mag.webp'),
    },
    {
        name: 'Mag Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'magnetic',
        hasLeverian: false,
        releaseYear: 2013,
        image: require('../assets/webp/mag-prime.webp'),
    },
    {
        name: 'Mesa',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'magnetic',
        hasLeverian: false,
        releaseYear: 2014,
        image: require('../assets/webp/mesa.webp'),
    },
    {
        name: 'Mesa Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'magnetic',
        hasLeverian: false,
        releaseYear: 2018,
        image: require('../assets/webp/mesa-prime.webp'),
    },
    {
        name: 'Mirage',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        hasLeverian: false,
        releaseYear: 2014,
        image: require('../assets/webp/mirage.webp'),
    },
    {
        name: 'Mirage Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        hasLeverian: false,
        releaseYear: 2017,
        image: require('../assets/webp/mirage-prime.webp'),
    },
    {
        name: 'Nekros',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['none'],
        progenitorElement: 'toxin',
        hasLeverian: false,
        releaseYear: 2013,
        image: require('../assets/webp/nekros.webp'),
    },
    {
        name: 'Nekros Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['none'],
        progenitorElement: 'toxin',
        hasLeverian: false,
        releaseYear: 2016,
        image: require('../assets/webp/nekros-prime.webp'),
    },
    {
        name: 'Nezha',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        hasLeverian: true,
        releaseYear: 2015,
        image: require('../assets/webp/nezha.webp'),
    },
    {
        name: 'Nezha Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        hasLeverian: true,
        releaseYear: 2020,
        image: require('../assets/webp/nezha-prime.webp'),
    },
    {
        name: 'Nidus',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'toxin',
        hasLeverian: false,
        releaseYear: 2016,
        image: require('../assets/webp/nidus.webp'),
    },
    {
        name: 'Nidus Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'toxin',
        hasLeverian: false,
        releaseYear: 2021,
        image: require('../assets/webp/nidus-prime.webp'),
    },
    {
        name: 'Nova',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'electricity',
        hasLeverian: true,
        releaseYear: 2013,
        image: require('../assets/webp/nova.webp'),
    },
    {
        name: 'Nova Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'electricity',
        hasLeverian: true,
        releaseYear: 2014,
        image: require('../assets/webp/nova-prime.webp'),
    },
    {
        name: 'Nyx',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        hasLeverian: false,
        releaseYear: 2013,
        image: require('../assets/webp/nyx.webp'),
    },
    {
        name: 'Nyx Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        hasLeverian: false,
        releaseYear: 2014,
        image: require('../assets/webp/nyx-prime.webp'),
    },
    {
        name: 'Oberon',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'toxin',
        hasLeverian: false,
        releaseYear: 2013,
        image: require('../assets/webp/oberon.webp'),
    },
    {
        name: 'Oberon Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'toxin',
        hasLeverian: false,
        releaseYear: 2017,
        image: require('../assets/webp/oberon-prime.webp'),
    },
    {
        name: 'Octavia',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        hasLeverian: false,
        releaseYear: 2017,
        image: require('../assets/webp/octavia.webp'),
    },
    {
        name: 'Octavia Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        hasLeverian: false,
        releaseYear: 2021,
        image: require('../assets/webp/octavia-prime.webp'),
    },
    {
        name: 'Protea',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['universal'],
        progenitorElement: 'heat',
        hasLeverian: false,
        releaseYear: 2020,
        image: require('../assets/webp/protea.webp'),
    },
    {
        name: 'Protea Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['universal'],
        progenitorElement: 'heat',
        hasLeverian: false,
        releaseYear: 2024,
        image: require('../assets/webp/protea-prime.webp'),
    },
    {
        name: 'Qorvex',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'radiation',
        hasLeverian: false,
        releaseYear: 2023,
        image: require('../assets/webp/qorvex.webp'),
    },
    {
        name: 'Revenant',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'cold',
        hasLeverian: false,
        releaseYear: 2018,
        image: require('../assets/webp/revenant.webp'),
    },
    {
        name: 'Revenant Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'cold',
        hasLeverian: false,
        releaseYear: 2022,
        image: require('../assets/webp/revenant-prime.webp'),
    },
    {
        name: 'Rhino',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'impact',
        hasLeverian: false,
        releaseYear: 2012,
        image: require('../assets/webp/rhino.webp'),
    },
    {
        name: 'Rhino Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'impact',
        hasLeverian: false,
        releaseYear: 2014,
        image: require('../assets/webp/rhino-prime.webp'),
    },
    {
        name: 'Saryn',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'toxin',
        hasLeverian: false,
        releaseYear: 2013,
        image: require('../assets/webp/saryn.webp'),
    },
    {
        name: 'Saryn Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['vazarin'],
        progenitorElement: 'toxin',
        hasLeverian: false,
        releaseYear: 2016,
        image: require('../assets/webp/saryn-prime.webp'),
    },
    {
        name: 'Sevagoth',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['none'],
        progenitorElement: 'impact',
        hasLeverian: false,
        releaseYear: 2021,
        image: require('../assets/webp/sevagoth.webp'),
    },
    {
        name: 'Sevagoth Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['none'],
        progenitorElement: 'impact',
        hasLeverian: false,
        releaseYear: 2024,
        image: require('../assets/webp/sevagoth-prime.webp'),
    },
    {
        name: 'Styanax',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'cold',
        hasLeverian: true,
        releaseYear: 2022,
        image: require('../assets/webp/styanax.webp'),
    },
    {
        name: 'Temple',
        gender: 'non binary',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        hasLeverian: true,
        releaseYear: 2025,
        image: require('../assets/webp/styanax.webp'),
    },
    {
        name: 'Titania',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'cold',
        hasLeverian: false,
        releaseYear: 2016,
        image: require('../assets/webp/titania.webp'),
    },
    {
        name: 'Titania Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'cold',
        hasLeverian: false,
        releaseYear: 2020,
        image: require('../assets/webp/titania-prime.webp'),
    },
    {
        name: 'Trinity',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'cold',
        hasLeverian: false,
        releaseYear: 2012,
        image: require('../assets/webp/trinity.webp'),
    },
    {
        name: 'Trinity Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['vazarin'],
        progenitorElement: 'cold',
        hasLeverian: false,
        releaseYear: 2015,
        image: require('../assets/webp/trinity-prime.webp'),
    },
    {
        name: 'Valkyr',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        hasLeverian: false,
        releaseYear: 2013,
        image: require('../assets/webp/valkyr.webp'),
    },
    {
        name: 'Valkyr Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        hasLeverian: false,
        releaseYear: 2016,
        image: require('../assets/webp/valkyr-prime.webp'),
    },
    {
        name: 'Vauban',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        hasLeverian: false,
        releaseYear: 2013,
        image: require('../assets/webp/vauban.webp'),
    },
    {
        name: 'Vauban Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        hasLeverian: false,
        releaseYear: 2016,
        image: require('../assets/webp/vauban-prime.webp'),
    },
    {
        name: 'Volt',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        hasLeverian: false,
        releaseYear: 2012,
        image: require('../assets/webp/volt.webp'),
    },
    {
        name: 'Volt Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        hasLeverian: false,
        releaseYear: 2015,
        image: require('../assets/webp/volt-prime.webp'),
    },
    {
        name: 'Voruna',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'radiation',
        hasLeverian: true,
        releaseYear: 2022,
        image: require('../assets/webp/voruna.webp'),
    },
    {
        name: 'Wisp',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        hasLeverian: false,
        releaseYear: 2019,
        image: require('../assets/webp/wisp.webp'),
    },
    {
        name: 'Wisp Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        hasLeverian: false,
        releaseYear: 2023,
        image: require('../assets/webp/wisp-prime.webp'),
    },
    {
        name: 'Wukong',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'impact',
        hasLeverian: false,
        releaseYear: 2015,
        image: require('../assets/webp/wukong.webp'),
    },
    {
        name: 'Wukong Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'impact',
        hasLeverian: false,
        releaseYear: 2019,
        image: require('../assets/webp/wukong-prime.webp'),
    },
    {
        name: 'Xaku',
        gender: 'non binary',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        hasLeverian: false,
        releaseYear: 2020,
        image: require('../assets/webp/xaku.webp'),
    },
    {
        name: 'Xaku Prime',
        gender: 'non binary',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        hasLeverian: false,
        releaseYear: 2024,
        image: require('../assets/webp/xaku-prime.webp'),
    },
    {
        name: 'Yareli',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'magnetic',
        hasLeverian: false,
        releaseYear: 2021,
        image: require('../assets/webp/yareli.webp'),
    },
    {
        name: 'Yareli Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'magnetic',
        hasLeverian: false,
        releaseYear: 2025,
        image: require('../assets/webp/yareli.webp'),
    },
    {
        name: 'Zephyr',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'impact',
        hasLeverian: false,
        releaseYear: 2014,
        image: require('../assets/webp/zephyr.webp'),
    },
    {
        name: 'Zephyr Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['vazarin'],
        progenitorElement: 'impact',
        hasLeverian: false,
        releaseYear: 2018,
        image: require('../assets/webp/zephyr-prime.webp'),
    },
];
