export const initialWarframes: Warframe[] = [
    {
        name: 'Ash',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'radiation',
        releaseYear: 2012,
        image: '/warframe_portraits/ash.webp',
    },
    {
        name: 'Ash Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'radiation',
        releaseYear: 2015,
        image: '/warframe_portraits/ash-prime.webp',
    },
    {
        name: 'Atlas',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'toxin',
        releaseYear: 2015,
        image: '/warframe_portraits/atlas.webp',
    },
    {
        name: 'Atlas Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'toxin',
        releaseYear: 2019,
        image: '/warframe_portraits/atlas-prime.webp',
    },
    {
        name: 'Banshee',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        releaseYear: 2013,
        image: '/warframe_portraits/banshee.webp',
    },
    {
        name: 'Banshee Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        releaseYear: 2017,
        image: '/warframe_portraits/banshee-prime.webp',
    },
    {
        name: 'Baruuk',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'impact',
        releaseYear: 2018,
        image: '/warframe_portraits/baruuk.webp',
    },
    {
        name: 'Baruuk Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'impact',
        releaseYear: 2022,
        image: '/warframe_portraits/baruuk-prime.webp',
    },
    {
        name: 'Caliban',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'electricity',
        releaseYear: 2021,
        image: '/warframe_portraits/caliban.webp',
    },
    {
        name: 'Chroma',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'heat',
        releaseYear: 2015,
        image: '/warframe_portraits/chroma.webp',
    },
    {
        name: 'Chroma Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'heat',
        releaseYear: 2018,
        image: '/warframe_portraits/chroma-prime.webp',
    },
    {
        name: 'Citrine',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        releaseYear: 2023,
        image: '/warframe_portraits/citrine.webp',
    },
    {
        name: 'Cyte-09',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'magnetic',
        releaseYear: 2024,
        image: '/warframe_portraits/cyte-09.webp',
    },
    {
        name: 'Dagath',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['zenurik'],
        progenitorElement: 'toxin',
        releaseYear: 2023,
        image: '/warframe_portraits/dagath.webp',
    },
    {
        name: 'Dante',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['universal'],
        progenitorElement: 'impact',
        releaseYear: 2024,
        image: '/warframe_portraits/dante.webp',
    },
    {
        name: 'Ember',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'heat',
        releaseYear: 2012,
        image: '/warframe_portraits/ember.webp',
    },
    {
        name: 'Ember Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'heat',
        releaseYear: 2013,
        image: '/warframe_portraits/ember-prime.webp',
    },
    {
        name: 'Equinox',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        releaseYear: 2015,
        image: '/warframe_portraits/equinox.webp',
    },
    {
        name: 'Equinox Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        releaseYear: 2019,
        image: '/warframe_portraits/equinox-prime.webp',
    },
    {
        name: 'Excalibur',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['none'],
        progenitorElement: 'electricity',
        releaseYear: 2012,
        image: '/warframe_portraits/excalibur.webp',
    },
    {
        name: 'Excalibur Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        releaseYear: 2012,
        image: '/warframe_portraits/excalibur-prime.webp',
    },
    {
        name: 'Excalibur Umbra',
        gender: 'male',
        primeUmbra: 'umbra',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        releaseYear: 2018,
        image: '/warframe_portraits/excalibur-umbra.webp',
    },
    {
        name: 'Frost',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'cold',
        releaseYear: 2013,
        image: '/warframe_portraits/frost.webp',
    },
    {
        name: 'Frost Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['vazarin'],
        progenitorElement: 'cold',
        releaseYear: 2013,
        image: '/warframe_portraits/frost-prime.webp',
    },
    {
        name: 'Gara',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'cold',
        releaseYear: 2017,
        image: '/warframe_portraits/gara.webp',
    },
    {
        name: 'Gara Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['vazarin'],
        progenitorElement: 'cold',
        releaseYear: 2021,
        image: '/warframe_portraits/gara-prime.webp',
    },
    {
        name: 'Garuda',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'radiation',
        releaseYear: 2018,
        image: '/warframe_portraits/garuda.webp',
    },
    {
        name: 'Garuda Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'radiation',
        releaseYear: 2022,
        image: '/warframe_portraits/garuda-prime.webp',
    },
    {
        name: 'Gauss',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'impact',
        releaseYear: 2019,
        image: '/warframe_portraits/gauss.webp',
    },
    {
        name: 'Gauss Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'impact',
        releaseYear: 2024,
        image: '/warframe_portraits/gauss-prime.webp',
    },
    {
        name: 'Grendel',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'impact',
        releaseYear: 2019,
        image: '/warframe_portraits/grendel.webp',
    },
    {
        name: 'Grendel Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'impact',
        releaseYear: 2023,
        image: '/warframe_portraits/grendel-prime.webp',
    },
    {
        name: 'Gyre',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'electricity',
        releaseYear: 2022,
        image: '/warframe_portraits/gyre.webp',
    },
    {
        name: 'Harrow',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        releaseYear: 2017,
        image: '/warframe_portraits/harrow.webp',
    },
    {
        name: 'Harrow Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        releaseYear: 2021,
        image: '/warframe_portraits/harrow-prime.webp',
    },
    {
        name: 'Hildryn',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'cold',
        releaseYear: 2019,
        image: '/warframe_portraits/hildryn.webp',
    },
    {
        name: 'Hildryn Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'cold',
        releaseYear: 2023,
        image: '/warframe_portraits/hildryn-prime.webp',
    },
    {
        name: 'Hydroid',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        releaseYear: 2014,
        image: '/warframe_portraits/hydroid.webp',
    },
    {
        name: 'Hydroid Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        releaseYear: 2017,
        image: '/warframe_portraits/hydroid-prime.webp',
    },
    {
        name: 'Inaros',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        releaseYear: 2016,
        image: '/warframe_portraits/inaros.webp',
    },
    {
        name: 'Inaros Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        releaseYear: 2020,
        image: '/warframe_portraits/inaros-prime.webp',
    },
    {
        name: 'Ivara',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'toxin',
        releaseYear: 2015,
        image: '/warframe_portraits/ivara.webp',
    },
    {
        name: 'Ivara Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'toxin',
        releaseYear: 2019,
        image: '/warframe_portraits/ivara-prime.webp',
    },
    {
        name: 'Jade',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['universal', 'madurai'],
        progenitorElement: 'heat',
        releaseYear: 2024,
        image: '/warframe_portraits/jade.webp',
    },
    {
        name: 'Khora',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'toxin',
        releaseYear: 2018,
        image: '/warframe_portraits/khora.webp',
    },
    {
        name: 'Khora Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['vazarin'],
        progenitorElement: 'toxin',
        releaseYear: 2022,
        image: '/warframe_portraits/khora-prime.webp',
    },
    {
        name: 'Koumei',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'cold',
        releaseYear: 2024,
        image: '/warframe_portraits/koumei.webp',
    },
    {
        name: 'Kullervo',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        releaseYear: 2023,
        image: '/warframe_portraits/kullervo.webp',
    },
    {
        name: 'Lavos',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        releaseYear: 2020,
        image: '/warframe_portraits/lavos.webp',
    },
    {
        name: 'Lavos Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        releaseYear: 2025,
        image: '/warframe_portraits/lavos-prime.webp',
    },
    {
        name: 'Limbo',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'electricity',
        releaseYear: 2014,
        image: '/warframe_portraits/limbo.webp',
    },
    {
        name: 'Limbo Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'electricity',
        releaseYear: 2018,
        image: '/warframe_portraits/limbo-prime.webp',
    },
    {
        name: 'Loki',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        releaseYear: 2012,
        image: '/warframe_portraits/loki.webp',
    },
    {
        name: 'Loki Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        releaseYear: 2014,
        image: '/warframe_portraits/loki-prime.webp',
    },
    {
        name: 'Mag',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'magnetic',
        releaseYear: 2012,
        image: '/warframe_portraits/mag.webp',
    },
    {
        name: 'Mag Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'magnetic',
        releaseYear: 2013,
        image: '/warframe_portraits/mag-prime.webp',
    },
    {
        name: 'Mesa',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'magnetic',
        releaseYear: 2014,
        image: '/warframe_portraits/mesa.webp',
    },
    {
        name: 'Mesa Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'magnetic',
        releaseYear: 2018,
        image: '/warframe_portraits/mesa-prime.webp',
    },
    {
        name: 'Mirage',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        releaseYear: 2014,
        image: '/warframe_portraits/mirage.webp',
    },
    {
        name: 'Mirage Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        releaseYear: 2017,
        image: '/warframe_portraits/mirage-prime.webp',
    },
    {
        name: 'Nekros',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['none'],
        progenitorElement: 'toxin',
        releaseYear: 2013,
        image: '/warframe_portraits/nekros.webp',
    },
    {
        name: 'Nekros Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['none'],
        progenitorElement: 'toxin',
        releaseYear: 2016,
        image: '/warframe_portraits/nekros-prime.webp',
    },
    {
        name: 'Nezha',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        releaseYear: 2015,
        image: '/warframe_portraits/nezha.webp',
    },
    {
        name: 'Nezha Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        releaseYear: 2020,
        image: '/warframe_portraits/nezha-prime.webp',
    },
    {
        name: 'Nidus',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'toxin',
        releaseYear: 2016,
        image: '/warframe_portraits/nidus.webp',
    },
    {
        name: 'Nidus Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'toxin',
        releaseYear: 2021,
        image: '/warframe_portraits/nidus-prime.webp',
    },
    {
        name: 'Nova',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'electricity',
        releaseYear: 2013,
        image: '/warframe_portraits/nova.webp',
    },
    {
        name: 'Nova Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'electricity',
        releaseYear: 2014,
        image: '/warframe_portraits/nova-prime.webp',
    },
    {
        name: 'Nyx',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        releaseYear: 2013,
        image: '/warframe_portraits/nyx.webp',
    },
    {
        name: 'Nyx Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        releaseYear: 2014,
        image: '/warframe_portraits/nyx-prime.webp',
    },
    {
        name: 'Oberon',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'toxin',
        releaseYear: 2013,
        image: '/warframe_portraits/oberon.webp',
    },
    {
        name: 'Oberon Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'toxin',
        releaseYear: 2017,
        image: '/warframe_portraits/oberon-prime.webp',
    },
    {
        name: 'Octavia',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        releaseYear: 2017,
        image: '/warframe_portraits/octavia.webp',
    },
    {
        name: 'Octavia Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'radiation',
        releaseYear: 2021,
        image: '/warframe_portraits/octavia-prime.webp',
    },
    {
        name: 'Oraxia',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'toxin',
        releaseYear: 2025,
        image: '/warframe_portraits/oraxia.webp',
    },
    {
        name: 'Protea',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['universal'],
        progenitorElement: 'heat',
        releaseYear: 2020,
        image: '/warframe_portraits/protea.webp',
    },
    {
        name: 'Protea Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['universal'],
        progenitorElement: 'heat',
        releaseYear: 2024,
        image: '/warframe_portraits/protea-prime.webp',
    },
    {
        name: 'Qorvex',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'radiation',
        releaseYear: 2023,
        image: '/warframe_portraits/qorvex.webp',
    },
    {
        name: 'Revenant',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'cold',
        releaseYear: 2018,
        image: '/warframe_portraits/revenant.webp',
    },
    {
        name: 'Revenant Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'cold',
        releaseYear: 2022,
        image: '/warframe_portraits/revenant-prime.webp',
    },
    {
        name: 'Rhino',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'impact',
        releaseYear: 2012,
        image: '/warframe_portraits/rhino.webp',
    },
    {
        name: 'Rhino Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'impact',
        releaseYear: 2014,
        image: '/warframe_portraits/rhino-prime.webp',
    },
    {
        name: 'Saryn',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'toxin',
        releaseYear: 2013,
        image: '/warframe_portraits/saryn.webp',
    },
    {
        name: 'Saryn Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['vazarin'],
        progenitorElement: 'toxin',
        releaseYear: 2016,
        image: '/warframe_portraits/saryn-prime.webp',
    },
    {
        name: 'Sevagoth',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['none'],
        progenitorElement: 'impact',
        releaseYear: 2021,
        image: '/warframe_portraits/sevagoth.webp',
    },
    {
        name: 'Sevagoth Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['none'],
        progenitorElement: 'impact',
        releaseYear: 2024,
        image: '/warframe_portraits/sevagoth-prime.webp',
    },
    {
        name: 'Styanax',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'cold',
        releaseYear: 2022,
        image: '/warframe_portraits/styanax.webp',
    },
    {
        name: 'Temple',
        gender: 'non binary',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        releaseYear: 2025,
        image: '/warframe_portraits/temple.webp',
    },
    {
        name: 'Titania',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'cold',
        releaseYear: 2016,
        image: '/warframe_portraits/titania.webp',
    },
    {
        name: 'Titania Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'cold',
        releaseYear: 2020,
        image: '/warframe_portraits/titania-prime.webp',
    },
    {
        name: 'Trinity',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'cold',
        releaseYear: 2012,
        image: '/warframe_portraits/trinity.webp',
    },
    {
        name: 'Trinity Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['vazarin'],
        progenitorElement: 'cold',
        releaseYear: 2015,
        image: '/warframe_portraits/trinity-prime.webp',
    },
    {
        name: 'Valkyr',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        releaseYear: 2013,
        image: '/warframe_portraits/valkyr.webp',
    },
    {
        name: 'Valkyr Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        releaseYear: 2016,
        image: '/warframe_portraits/valkyr-prime.webp',
    },
    {
        name: 'Vauban',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        releaseYear: 2013,
        image: '/warframe_portraits/vauban.webp',
    },
    {
        name: 'Vauban Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        releaseYear: 2016,
        image: '/warframe_portraits/vauban-prime.webp',
    },
    {
        name: 'Volt',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        releaseYear: 2012,
        image: '/warframe_portraits/volt.webp',
    },
    {
        name: 'Volt Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'electricity',
        releaseYear: 2015,
        image: '/warframe_portraits/volt-prime.webp',
    },
    {
        name: 'Voruna',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'radiation',
        releaseYear: 2022,
        image: '/warframe_portraits/voruna.webp',
    },
    {
        name: 'Wisp',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        releaseYear: 2019,
        image: '/warframe_portraits/wisp.webp',
    },
    {
        name: 'Wisp Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'heat',
        releaseYear: 2023,
        image: '/warframe_portraits/wisp-prime.webp',
    },
    {
        name: 'Wukong',
        gender: 'male',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'impact',
        releaseYear: 2015,
        image: '/warframe_portraits/wukong.webp',
    },
    {
        name: 'Wukong Prime',
        gender: 'male',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'impact',
        releaseYear: 2019,
        image: '/warframe_portraits/wukong-prime.webp',
    },
    {
        name: 'Xaku',
        gender: 'non binary',
        primeUmbra: 'standard',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        releaseYear: 2020,
        image: '/warframe_portraits/xaku.webp',
    },
    {
        name: 'Xaku Prime',
        gender: 'non binary',
        primeUmbra: 'prime',
        auraPolarity: ['naramon'],
        progenitorElement: 'magnetic',
        releaseYear: 2024,
        image: '/warframe_portraits/xaku-prime.webp',
    },
    {
        name: 'Yareli',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['madurai'],
        progenitorElement: 'magnetic',
        releaseYear: 2021,
        image: '/warframe_portraits/yareli.webp',
    },
    {
        name: 'Yareli Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['madurai'],
        progenitorElement: 'magnetic',
        releaseYear: 2025,
        image: '/warframe_portraits/yareli-prime.webp',
    },
    {
        name: 'Zephyr',
        gender: 'female',
        primeUmbra: 'standard',
        auraPolarity: ['vazarin'],
        progenitorElement: 'impact',
        releaseYear: 2014,
        image: '/warframe_portraits/zephyr.webp',
    },
    {
        name: 'Zephyr Prime',
        gender: 'female',
        primeUmbra: 'prime',
        auraPolarity: ['vazarin'],
        progenitorElement: 'impact',
        releaseYear: 2018,
        image: '/warframe_portraits/zephyr-prime.webp',
    },
];
