export const initialWarframes: Warframe[] = [
    {
        name: "Ash",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "radiation",
        releaseYear: 2012,
        image: "/warframe_portraits/ash.webp",
        playstyle: ["stealth", "damage"],
    },
    {
        name: "Ash Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "radiation",
        releaseYear: 2015,
        image: "/warframe_portraits/ash-prime.webp",
        playstyle: ["stealth", "damage"],
    },
    {
        name: "Atlas",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "toxin",
        releaseYear: 2015,
        image: "/warframe_portraits/atlas.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Atlas Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "toxin",
        releaseYear: 2019,
        image: "/warframe_portraits/atlas-prime.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Banshee",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "electricity",
        releaseYear: 2013,
        image: "/warframe_portraits/banshee.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Banshee Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "electricity",
        releaseYear: 2017,
        image: "/warframe_portraits/banshee-prime.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Baruuk",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "impact",
        releaseYear: 2018,
        image: "/warframe_portraits/baruuk.webp",
        playstyle: ["damage", "crowd-control"],
    },
    {
        name: "Baruuk Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "impact",
        releaseYear: 2022,
        image: "/warframe_portraits/baruuk-prime.webp",
        playstyle: ["damage", "crowd-control"],
    },
    {
        name: "Caliban",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "electricity",
        releaseYear: 2021,
        image: "/warframe_portraits/caliban.webp",
        playstyle: ["survival", "crowd-control"],
    },
    {
        name: "Caliban Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "electricity",
        releaseYear: 2025,
        image: "/warframe_portraits/caliban-prime.webp",
        playstyle: ["survival", "crowd-control"],
    },
    {
        name: "Chroma",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "heat",
        releaseYear: 2015,
        image: "/warframe_portraits/chroma.webp",
        playstyle: ["survival", "damage"],
    },
    {
        name: "Chroma Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "heat",
        releaseYear: 2018,
        image: "/warframe_portraits/chroma-prime.webp",
        playstyle: ["survival", "damage"],
    },
    {
        name: "Citrine",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "magnetic",
        releaseYear: 2023,
        image: "/warframe_portraits/citrine.webp",
        playstyle: ["support"],
    },
    {
        name: "Cyte-09",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "magnetic",
        releaseYear: 2024,
        image: "/warframe_portraits/cyte-09.webp",
        playstyle: ["damage", "stealth"],
    },
    {
        name: "Dagath",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["zenurik"],
        progenitorElement: "toxin",
        releaseYear: 2023,
        image: "/warframe_portraits/dagath.webp",
        playstyle: ["damage"],
    },
    {
        name: "Dante",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["universal"],
        progenitorElement: "impact",
        releaseYear: 2024,
        image: "/warframe_portraits/dante.webp",
        playstyle: ["damage", "support", "survival"],
    },
    {
        name: "Ember",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "heat",
        releaseYear: 2012,
        image: "/warframe_portraits/ember.webp",
        playstyle: ["damage"],
    },
    {
        name: "Ember Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "heat",
        releaseYear: 2013,
        image: "/warframe_portraits/ember-prime.webp",
        playstyle: ["damage"],
    },
    {
        name: "Equinox",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "radiation",
        releaseYear: 2015,
        image: "/warframe_portraits/equinox.webp",
        playstyle: ["support"],
    },
    {
        name: "Equinox Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "radiation",
        releaseYear: 2019,
        image: "/warframe_portraits/equinox-prime.webp",
        playstyle: ["support"],
    },
    {
        name: "Excalibur",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["none"],
        progenitorElement: "electricity",
        releaseYear: 2012,
        image: "/warframe_portraits/excalibur.webp",
        playstyle: ["damage"],
    },
    {
        name: "Excalibur Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "electricity",
        releaseYear: 2012,
        image: "/warframe_portraits/excalibur-prime.webp",
        playstyle: ["damage"],
    },
    {
        name: "Excalibur Umbra",
        gender: "male",
        primeUmbra: "umbra",
        auraPolarity: ["madurai"],
        progenitorElement: "electricity",
        releaseYear: 2018,
        image: "/warframe_portraits/excalibur-umbra.webp",
        playstyle: ["damage"],
    },
    {
        name: "Frost",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["vazarin"],
        progenitorElement: "cold",
        releaseYear: 2013,
        image: "/warframe_portraits/frost.webp",
        playstyle: ["crowd-control", "survival"],
    },
    {
        name: "Frost Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["vazarin"],
        progenitorElement: "cold",
        releaseYear: 2013,
        image: "/warframe_portraits/frost-prime.webp",
        playstyle: ["crowd-control", "survival"],
    },
    {
        name: "Gara",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["vazarin"],
        progenitorElement: "cold",
        releaseYear: 2017,
        image: "/warframe_portraits/gara.webp",
        playstyle: ["damage", "survival", "crowd-control"],
    },
    {
        name: "Gara Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["vazarin"],
        progenitorElement: "cold",
        releaseYear: 2021,
        image: "/warframe_portraits/gara-prime.webp",
        playstyle: ["damage", "survival", "crowd-control"],
    },
    {
        name: "Garuda",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "radiation",
        releaseYear: 2018,
        image: "/warframe_portraits/garuda.webp",
        playstyle: ["damage"],
    },
    {
        name: "Garuda Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "radiation",
        releaseYear: 2022,
        image: "/warframe_portraits/garuda-prime.webp",
        playstyle: ["damage"],
    },
    {
        name: "Gauss",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "impact",
        releaseYear: 2019,
        image: "/warframe_portraits/gauss.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Gauss Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "impact",
        releaseYear: 2024,
        image: "/warframe_portraits/gauss-prime.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Grendel",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "impact",
        releaseYear: 2019,
        image: "/warframe_portraits/grendel.webp",
        playstyle: ["survival"],
    },
    {
        name: "Grendel Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "impact",
        releaseYear: 2023,
        image: "/warframe_portraits/grendel-prime.webp",
        playstyle: ["survival"],
    },
    {
        name: "Gyre",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "electricity",
        releaseYear: 2022,
        image: "/warframe_portraits/gyre.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Harrow",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "magnetic",
        releaseYear: 2017,
        image: "/warframe_portraits/harrow.webp",
        playstyle: ["survival", "support"],
    },
    {
        name: "Harrow Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "magnetic",
        releaseYear: 2021,
        image: "/warframe_portraits/harrow-prime.webp",
        playstyle: ["survival", "support"],
    },
    {
        name: "Hildryn",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "cold",
        releaseYear: 2019,
        image: "/warframe_portraits/hildryn.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Hildryn Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "cold",
        releaseYear: 2023,
        image: "/warframe_portraits/hildryn-prime.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Hydroid",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "magnetic",
        releaseYear: 2014,
        image: "/warframe_portraits/hydroid.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Hydroid Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "magnetic",
        releaseYear: 2017,
        image: "/warframe_portraits/hydroid-prime.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Inaros",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "heat",
        releaseYear: 2016,
        image: "/warframe_portraits/inaros.webp",
        playstyle: ["survival", "crowd-control"],
    },
    {
        name: "Inaros Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "heat",
        releaseYear: 2020,
        image: "/warframe_portraits/inaros-prime.webp",
        playstyle: ["survival", "crowd-control"],
    },
    {
        name: "Ivara",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "toxin",
        releaseYear: 2015,
        image: "/warframe_portraits/ivara.webp",
        playstyle: ["stealth"],
    },
    {
        name: "Ivara Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "toxin",
        releaseYear: 2019,
        image: "/warframe_portraits/ivara-prime.webp",
        playstyle: ["stealth"],
    },
    {
        name: "Jade",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["universal", "madurai"],
        progenitorElement: "heat",
        releaseYear: 2024,
        image: "/warframe_portraits/jade.webp",
        playstyle: ["support"],
    },
    {
        name: "Khora",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["vazarin"],
        progenitorElement: "toxin",
        releaseYear: 2018,
        image: "/warframe_portraits/khora.webp",
        playstyle: ["crowd-control", "damage"],
    },
    {
        name: "Khora Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["vazarin"],
        progenitorElement: "toxin",
        releaseYear: 2022,
        image: "/warframe_portraits/khora-prime.webp",
        playstyle: ["crowd-control", "damage"],
    },
    {
        name: "Koumei",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "cold",
        releaseYear: 2024,
        image: "/warframe_portraits/koumei.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Kullervo",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "heat",
        releaseYear: 2023,
        image: "/warframe_portraits/kullervo.webp",
        playstyle: ["damage"],
    },
    {
        name: "Lavos",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "magnetic",
        releaseYear: 2020,
        image: "/warframe_portraits/lavos.webp",
        playstyle: ["damage"],
    },
    {
        name: "Lavos Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "magnetic",
        releaseYear: 2025,
        image: "/warframe_portraits/lavos_prime.webp",
        playstyle: ["damage"],
    },
    {
        name: "Limbo",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "electricity",
        releaseYear: 2014,
        image: "/warframe_portraits/limbo.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Limbo Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "electricity",
        releaseYear: 2018,
        image: "/warframe_portraits/limbo-prime.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Loki",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "radiation",
        releaseYear: 2012,
        image: "/warframe_portraits/loki.webp",
        playstyle: ["stealth"],
    },
    {
        name: "Loki Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "radiation",
        releaseYear: 2014,
        image: "/warframe_portraits/loki-prime.webp",
        playstyle: ["stealth"],
    },
    {
        name: "Mag",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "magnetic",
        releaseYear: 2012,
        image: "/warframe_portraits/mag.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Mag Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "magnetic",
        releaseYear: 2013,
        image: "/warframe_portraits/mag-prime.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Mesa",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "magnetic",
        releaseYear: 2014,
        image: "/warframe_portraits/mesa.webp",
        playstyle: ["damage"],
    },
    {
        name: "Mesa Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "magnetic",
        releaseYear: 2018,
        image: "/warframe_portraits/mesa-prime.webp",
        playstyle: ["damage"],
    },
    {
        name: "Mirage",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "radiation",
        releaseYear: 2014,
        image: "/warframe_portraits/mirage.webp",
        playstyle: ["damage"],
    },
    {
        name: "Mirage Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "radiation",
        releaseYear: 2017,
        image: "/warframe_portraits/mirage-prime.webp",
        playstyle: ["damage"],
    },
    {
        name: "Nekros",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["none"],
        progenitorElement: "toxin",
        releaseYear: 2013,
        image: "/warframe_portraits/nekros.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Nekros Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["none"],
        progenitorElement: "toxin",
        releaseYear: 2016,
        image: "/warframe_portraits/nekros-prime.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Nezha",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "heat",
        releaseYear: 2015,
        image: "/warframe_portraits/nezha.webp",
        playstyle: ["damage", "survival", "crowd-control"],
    },
    {
        name: "Nezha Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "heat",
        releaseYear: 2020,
        image: "/warframe_portraits/nezha-prime.webp",
        playstyle: ["damage", "survival", "crowd-control"],
    },
    {
        name: "Nidus",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "toxin",
        releaseYear: 2016,
        image: "/warframe_portraits/nidus.webp",
        playstyle: ["damage", "survival", "crowd-control"],
    },
    {
        name: "Nidus Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "toxin",
        releaseYear: 2021,
        image: "/warframe_portraits/nidus-prime.webp",
        playstyle: ["damage", "survival", "crowd-control"],
    },
    {
        name: "Nova",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "electricity",
        releaseYear: 2013,
        image: "/warframe_portraits/nova.webp",
        playstyle: ["damage"],
    },
    {
        name: "Nova Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "electricity",
        releaseYear: 2014,
        image: "/warframe_portraits/nova-prime.webp",
        playstyle: ["damage"],
    },
    {
        name: "Nyx",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "radiation",
        releaseYear: 2013,
        image: "/warframe_portraits/nyx.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Nyx Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "radiation",
        releaseYear: 2014,
        image: "/warframe_portraits/nyx-prime.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Oberon",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "toxin",
        releaseYear: 2013,
        image: "/warframe_portraits/oberon.webp",
        playstyle: ["support"],
    },
    {
        name: "Oberon Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "toxin",
        releaseYear: 2017,
        image: "/warframe_portraits/oberon-prime.webp",
        playstyle: ["support"],
    },
    {
        name: "Octavia",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "radiation",
        releaseYear: 2017,
        image: "/warframe_portraits/octavia.webp",
        playstyle: ["support", "damage", "crowd-control"],
    },
    {
        name: "Octavia Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "radiation",
        releaseYear: 2021,
        image: "/warframe_portraits/octavia-prime.webp",
        playstyle: ["support", "damage", "crowd-control"],
    },
    {
        name: "Oraxia",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "toxin",
        releaseYear: 2025,
        image: "/warframe_portraits/oraxia.webp",
        playstyle: ["damage", "stealth"],
    },
    {
        name: "Protea",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["universal"],
        progenitorElement: "heat",
        releaseYear: 2020,
        image: "/warframe_portraits/protea.webp",
        playstyle: ["damage", "support"],
    },
    {
        name: "Protea Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["universal"],
        progenitorElement: "heat",
        releaseYear: 2024,
        image: "/warframe_portraits/protea-prime.webp",
        playstyle: ["damage", "support"],
    },
    {
        name: "Qorvex",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["vazarin"],
        progenitorElement: "radiation",
        releaseYear: 2023,
        image: "/warframe_portraits/qorvex.webp",
        playstyle: ["survival", "crowd-control"],
    },
    {
        name: "Revenant",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "cold",
        releaseYear: 2018,
        image: "/warframe_portraits/revenant.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Revenant Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "cold",
        releaseYear: 2022,
        image: "/warframe_portraits/revenant-prime.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Rhino",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "impact",
        releaseYear: 2012,
        image: "/warframe_portraits/rhino.webp",
        playstyle: ["survival", "crowd-control"],
    },
    {
        name: "Rhino Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "impact",
        releaseYear: 2014,
        image: "/warframe_portraits/rhino-prime.webp",
        playstyle: ["survival", "crowd-control"],
    },
    {
        name: "Saryn",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["vazarin"],
        progenitorElement: "toxin",
        releaseYear: 2013,
        image: "/warframe_portraits/saryn.webp",
        playstyle: ["damage"],
    },
    {
        name: "Saryn Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["vazarin"],
        progenitorElement: "toxin",
        releaseYear: 2016,
        image: "/warframe_portraits/saryn-prime.webp",
        playstyle: ["damage"],
    },
    {
        name: "Sevagoth",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["none"],
        progenitorElement: "impact",
        releaseYear: 2021,
        image: "/warframe_portraits/sevagoth.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Sevagoth Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["none"],
        progenitorElement: "impact",
        releaseYear: 2024,
        image: "/warframe_portraits/sevagoth-prime.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Styanax",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "cold",
        releaseYear: 2022,
        image: "/warframe_portraits/styanax.webp",
        playstyle: ["damage"],
    },
    {
        name: "Temple",
        gender: "non binary",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "heat",
        releaseYear: 2025,
        image: "/warframe_portraits/temple.webp",
        playstyle: ["damage", "support"],
    },
    {
        name: "Titania",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "cold",
        releaseYear: 2016,
        image: "/warframe_portraits/titania.webp",
        playstyle: ["damage", "crowd-control"],
    },
    {
        name: "Titania Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "cold",
        releaseYear: 2020,
        image: "/warframe_portraits/titania-prime.webp",
        playstyle: ["damage", "crowd-control"],
    },
    {
        name: "Trinity",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["vazarin"],
        progenitorElement: "cold",
        releaseYear: 2012,
        image: "/warframe_portraits/trinity.webp",
        playstyle: ["survival", "support"],
    },
    {
        name: "Trinity Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["vazarin"],
        progenitorElement: "cold",
        releaseYear: 2015,
        image: "/warframe_portraits/trinity-prime.webp",
        playstyle: ["survival", "support"],
    },
    {
        name: "Valkyr",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "electricity",
        releaseYear: 2013,
        image: "/warframe_portraits/valkyr.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Valkyr Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "electricity",
        releaseYear: 2016,
        image: "/warframe_portraits/valkyr-prime.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Vauban",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "heat",
        releaseYear: 2013,
        image: "/warframe_portraits/vauban.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Vauban Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "heat",
        releaseYear: 2016,
        image: "/warframe_portraits/vauban-prime.webp",
        playstyle: ["crowd-control"],
    },
    {
        name: "Volt",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "electricity",
        releaseYear: 2012,
        image: "/warframe_portraits/volt.webp",
        playstyle: ["damage", "support"],
    },
    {
        name: "Volt Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "electricity",
        releaseYear: 2015,
        image: "/warframe_portraits/volt-prime.webp",
        playstyle: ["damage", "support"],
    },
    {
        name: "Voruna",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["vazarin"],
        progenitorElement: "radiation",
        releaseYear: 2022,
        image: "/warframe_portraits/voruna.webp",
        playstyle: ["damage", "stealth"],
    },
    {
        name: "Wisp",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "heat",
        releaseYear: 2019,
        image: "/warframe_portraits/wisp.webp",
        playstyle: ["support"],
    },
    {
        name: "Wisp Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "heat",
        releaseYear: 2023,
        image: "/warframe_portraits/wisp-prime.webp",
        playstyle: ["support"],
    },
    {
        name: "Wukong",
        gender: "male",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "impact",
        releaseYear: 2015,
        image: "/warframe_portraits/wukong.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Wukong Prime",
        gender: "male",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "impact",
        releaseYear: 2019,
        image: "/warframe_portraits/wukong-prime.webp",
        playstyle: ["damage", "survival"],
    },
    {
        name: "Xaku",
        gender: "non binary",
        primeUmbra: "standard",
        auraPolarity: ["naramon"],
        progenitorElement: "magnetic",
        releaseYear: 2020,
        image: "/warframe_portraits/xaku.webp",
        playstyle: ["damage"],
    },
    {
        name: "Xaku Prime",
        gender: "non binary",
        primeUmbra: "prime",
        auraPolarity: ["naramon"],
        progenitorElement: "magnetic",
        releaseYear: 2024,
        image: "/warframe_portraits/xaku-prime.webp",
        playstyle: ["damage"],
    },
    {
        name: "Yareli",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["madurai"],
        progenitorElement: "magnetic",
        releaseYear: 2021,
        image: "/warframe_portraits/yareli.webp",
        playstyle: ["damage", "crowd-control"],
    },
    {
        name: "Yareli Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["madurai"],
        progenitorElement: "magnetic",
        releaseYear: 2025,
        image: "/warframe_portraits/yareli-prime.webp",
        playstyle: ["damage", "crowd-control"],
    },
    {
        name: "Zephyr",
        gender: "female",
        primeUmbra: "standard",
        auraPolarity: ["vazarin"],
        progenitorElement: "impact",
        releaseYear: 2014,
        image: "/warframe_portraits/zephyr.webp",
        playstyle: ["damage", "crowd-control"],
    },
    {
        name: "Zephyr Prime",
        gender: "female",
        primeUmbra: "prime",
        auraPolarity: ["vazarin"],
        progenitorElement: "impact",
        releaseYear: 2018,
        image: "/warframe_portraits/zephyr-prime.webp",
        playstyle: ["damage", "crowd-control"],
    },
];
